### ISSUE TITLE
syncdb permissions issue

### ISSUE THREAD

**Issue by bunchc** [danielgroves/Vagrant-Tutorial#3]
```
TASK [deploy : Django syncdb] **************************************************
fatal: [default]: FAILED! => {"changed": false, "cmd": "./manage.py syncdb --noinput", "failed": true, "msg": "[Errno 13] Permission denied", "rc": 13}
```

I'm troubleshooting now.

**Comment by bunchc** [comment]
Worked through this. Turns out it was a difference in Django versions. For Django 1.10 on Ubuntu 16.04:

1) in app/vagranttest/vagranttest/urls.py
```
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'vagranttest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
]
```

2) In provision/deploy/tasks/main.yml remove the dbsync line

**Comment by danielgroves** [comment]
Hey @bunchc, thanks for looking into this. I've moved on past Vagrant a little in my dev environments now, so I've not updated this for a while. It would be _great_ if you could open a PR with your fix though, and I'll merge it in. Otherwise, I'll have a look at fixing it ASAP. 

Thanks!

**Comment by bunchc** [comment]
Sorry for the delay. I'll try to get this sorted today.

**Comment by danielgroves** [comment]
No worries -- I'm in no particular rush 🙂
